"""
Seed Data Generator

Uses an LLM with structured output to generate realistic synthetic CSV data
for a one-man physical goods e-commerce business based in Singapore.
Output files are written to backend/data/seed/.

Data generated by LLM:
    - 30 products (6 per category) with names, descriptions, and pricing
    - 5 suppliers (one per category) with contract notes
    - Supplier-to-category mapping
    - 3 partners with agreement descriptions and category preferences
    - 20 customer names

What is computed programmatically:
    - Orders          — random sampling of products × customers
    - Supply contracts — random quantities/lead times from LLM supplier data
    - Partner agreements — structured from LLM partner data
    - Partner products  — sampled from LLM category preferences

Usage:
    uv run python backend/data/generate_seed_data.py
"""

import csv
import random
from datetime import date, timedelta
from pathlib import Path
from typing import Literal

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

from backend.config import settings

SEED_DIR = Path(__file__).parent / "seed"

_PLATFORMS = ["WhatsApp", "Telegram", "Instagram DM", "Facebook Messenger", "Email"]
_CHANNELS = ["Shopee", "Lazada", "Carousell", "Website", "Instagram Shop"]
_ORDER_STATUSES = ["pending", "fulfilled", "cancelled"]
_CATEGORY = Literal["Electronics", "Apparel", "Home & Kitchen", "Sports & Outdoors", "Accessories"]


# ─── LLM output schema ────────────────────────────────────────────────────────

class _Product(BaseModel):
    name: str
    category: _CATEGORY
    cost_price: float = Field(gt=0, description="Wholesale cost in SGD")
    selling_price: float = Field(gt=0, description="Retail price in SGD — must exceed cost_price, target 40–150% margin")
    description: str = Field(description="One to two sentence customer-facing product description")


class _Supplier(BaseModel):
    name: str = Field(description="Chinese manufacturer or trading company name")
    category: _CATEGORY = Field(description="The single product category this supplier specialises in")
    contact_person: str
    email: str
    phone: str = Field(description="Chinese phone number, format: +86-...")
    typical_contract_notes: str = Field(
        description="Typical supply terms: payment schedule, MOQ, lead time expectations, preferred shipping method"
    )


class _Partner(BaseModel):
    name: str = Field(description="Southeast Asian reseller, affiliate, or collab business name")
    contact_person: str
    email: str
    phone: str
    agreement_type: Literal["reseller", "affiliate", "collab"]
    category_preferences: list[_CATEGORY] = Field(
        description="Product categories this partner focuses on (1–3 categories)",
    )
    agreement_description: str = Field(
        description="One sentence describing the partnership scope and commercial terms"
    )


class _SeedEntities(BaseModel):
    products: list[_Product] = Field(
        description="Exactly 30 products, 6 per category across all 5 categories"
    )
    suppliers: list[_Supplier] = Field(
        description="Exactly 5 suppliers, one per category, each from a different Chinese city"
    )
    partners: list[_Partner] = Field(
        description="Exactly 3 partners: one reseller, one affiliate, one collab"
    )
    customer_names: list[str] = Field(
        description="Exactly 20 full names of Singapore-based customers — realistic mix of Chinese, Malay, Indian, and expat names"
    )


# ─── LLM call ─────────────────────────────────────────────────────────────────

def _generate_entities() -> _SeedEntities:
    llm = ChatOpenAI(
        model=settings.OPENAI_MODEL,
        api_key=settings.OPENAI_API_KEY,
        temperature=1.0,
    )
    structured_llm = llm.with_structured_output(_SeedEntities)

    return structured_llm.invoke([
        SystemMessage(content=(
            "You are generating realistic synthetic seed data for a one-man e-commerce business "
            "based in Singapore that sells physical goods sourced from Chinese manufacturers. "
            "The business sells across Shopee, Lazada, Carousell, its own website, and Instagram Shop. "
            "Customers are primarily from Singapore with diverse ethnicities (Chinese, Malay, Indian, expat). "
            "Suppliers are Chinese B2B manufacturers based in different cities (Shenzhen, Guangzhou, Dongguan, etc.). "
            "Partners are Southeast Asian businesses (Singapore, Malaysia) acting as resellers, affiliates, or collaborators."
        )),
        HumanMessage(content=(
            "Generate seed data with:\n"
            "- 30 products split evenly across 5 categories (6 per category). "
            "Each product needs a name, realistic SGD pricing (selling_price > cost_price, 40–150% margin), "
            "and a descriptive one-to-two sentence customer-facing description.\n"
            "- 5 suppliers, one per category (Electronics, Apparel, Home & Kitchen, Sports & Outdoors, Accessories), "
            "each from a different Chinese city. Set the category field to the category they specialise in. "
            "Include realistic contract notes covering payment terms, MOQ, and shipping.\n"
            "- 3 partners: one reseller, one affiliate, one collab. Each with 1–3 category preferences "
            "and a one-sentence agreement description.\n"
            "- 20 Singapore customer full names with realistic ethnic diversity."
        )),
    ])


# ─── Row builders ─────────────────────────────────────────────────────────────

def generate_products(entities: _SeedEntities) -> list[dict]:
    rows = []
    for i, p in enumerate(entities.products, start=1):
        rows.append({
            "id": i,
            "name": p.name,
            "description": p.description,
            "selling_price": f"{p.selling_price:.2f}",
            "cost_price": f"{p.cost_price:.2f}",
            "stock_quantity": random.randint(10, 200),
            "category": p.category,
            "link": f"https://store.example.com/products/{p.name.lower().replace(' ', '-')}",
        })
    return rows


def generate_customers(entities: _SeedEntities) -> list[dict]:
    rows = []
    for i, name in enumerate(entities.customer_names, start=1):
        rows.append({
            "id": i,
            "name": name,
            "email": f"{name.lower().replace(' ', '.')}@email.com",
            "phone": f"+65-{random.randint(8000, 9999)}-{random.randint(1000, 9999)}",
            "address": (
                f"Blk {random.randint(100, 999)} "
                f"#{random.randint(1, 20):02d}-{random.randint(1, 200):03d}, "
                f"Singapore {random.randint(100000, 999999)}"
            ),
            "platform": random.choice(_PLATFORMS),
        })
    return rows


def generate_orders(products: list[dict], customers: list[dict]) -> list[dict]:
    rows = []
    start_date = date(2025, 1, 1)
    end_date = date(2026, 3, 15)
    delta_days = (end_date - start_date).days

    for i in range(1, 121):
        product = random.choice(products)
        customer = random.choice(customers)
        qty = random.randint(1, 5)
        order_date = start_date + timedelta(days=random.randint(0, delta_days))
        rows.append({
            "id": i,
            "customer_id": customer["id"],
            "product_id": product["id"],
            "quantity": qty,
            "total_price": f"{float(product['selling_price']) * qty:.2f}",
            "order_date": order_date.isoformat(),
            "status": random.choice(_ORDER_STATUSES),
            "channel": random.choice(_CHANNELS),
        })
    return rows


def generate_suppliers(entities: _SeedEntities) -> list[dict]:
    rows = []
    for i, s in enumerate(entities.suppliers, start=1):
        rows.append({
            "id": i,
            "name": s.name,
            "contact_person": s.contact_person,
            "email": s.email,
            "phone": s.phone,
        })
    return rows


def generate_supply_contracts(
    products: list[dict],
    suppliers: list[dict],
    entities: _SeedEntities,
) -> list[dict]:
    # Derive category → supplier mapping directly from the supplier's category field
    category_to_supplier_id = {s.category: sid for s, sid in
                                zip(entities.suppliers, [s["id"] for s in suppliers])}
    supplier_id_to_notes = {s["id"]: es.typical_contract_notes
                            for s, es in zip(suppliers, entities.suppliers)}
    rows = []
    contract_id = 1

    for product in products:
        supplier_id = category_to_supplier_id.get(product["category"])
        if not supplier_id:
            continue
        cost = float(product["cost_price"])
        rows.append({
            "id": contract_id,
            "supplier_id": supplier_id,
            "product_id": product["id"],
            "supply_price": f"{cost * random.uniform(0.85, 1.0):.2f}",
            "total_order_qty": random.choice([100, 200, 300, 500, 1000]),
            "lead_time_days": random.choice([7, 14, 21, 30, 45]),
            "contract_start": "2025-01-01",
            "contract_end": "2025-12-31",
            "is_active": True,
            "notes": supplier_id_to_notes.get(supplier_id, ""),
        })
        contract_id += 1
    return rows


def generate_partners(entities: _SeedEntities) -> list[dict]:
    rows = []
    for i, p in enumerate(entities.partners, start=1):
        rows.append({
            "id": i,
            "name": p.name,
            "contact_person": p.contact_person,
            "email": p.email,
            "phone": p.phone,
        })
    return rows


def generate_partner_agreements(
    partners: list[dict],
    entities: _SeedEntities,
) -> list[dict]:
    rows = []
    for i, (partner, ep) in enumerate(zip(partners, entities.partners), start=1):
        rows.append({
            "id": i,
            "partner_id": partner["id"],
            "description": ep.agreement_description,
            "agreement_type": ep.agreement_type,
            "revenue_share_pct": f"{random.uniform(5, 20):.2f}",
            "start_date": "2025-01-01",
            "end_date": "2025-12-31",
            "is_active": True,
            "notes": "",
        })
    return rows


def generate_partner_products(
    partners: list[dict],
    products: list[dict],
    entities: _SeedEntities,
) -> list[dict]:
    rows = []
    pp_id = 1
    for partner, ep in zip(partners, entities.partners):
        linked = [p for p in products if p["category"] in ep.category_preferences]
        for product in random.sample(linked, min(5, len(linked))):
            rows.append({
                "id": pp_id,
                "partner_id": partner["id"],
                "product_id": product["id"],
                "agreement_id": partner["id"],
            })
            pp_id += 1
    return rows


# ─── CSV writer ───────────────────────────────────────────────────────────────

def _write_csv(filename: str, rows: list[dict]) -> None:
    if not rows:
        return
    SEED_DIR.mkdir(parents=True, exist_ok=True)
    filepath = SEED_DIR / filename
    with open(filepath, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)
    print(f"  written {len(rows)} rows → {filepath}")


# ─── Main pipeline ────────────────────────────────────────────────────────────

def generate_all() -> None:
    random.seed(42)

    print("Calling LLM to generate entity data...")
    entities = _generate_entities()
    print("  entities received.")

    products = generate_products(entities)
    customers = generate_customers(entities)
    orders = generate_orders(products, customers)
    suppliers = generate_suppliers(entities)
    supply_contracts = generate_supply_contracts(products, suppliers, entities)
    partners = generate_partners(entities)
    agreements = generate_partner_agreements(partners, entities)
    partner_products = generate_partner_products(partners, products, entities)

    _write_csv("products.csv", products)
    _write_csv("customers.csv", customers)
    _write_csv("orders.csv", orders)
    _write_csv("suppliers.csv", suppliers)
    _write_csv("supply_contracts.csv", supply_contracts)
    _write_csv("partners.csv", partners)
    _write_csv("partner_agreements.csv", agreements)
    _write_csv("partner_products.csv", partner_products)

    print("Done.")


if __name__ == "__main__":
    generate_all()
