"""
A2A (Agent-to-Agent) Communication Contract

Standardized response format for all sub-agents returning data 
to the Orchestrator (Supervisor). This ensures consistent parsing, 
error handling, and risk evaluation down the pipeline.
"""

from typing import Literal
from pydantic import BaseModel, Field

class AgentResponse(BaseModel):
    """
    Standardized payload returned by sub-agents (Retrieval, Policy, Research, Memory Read).
    """
    status: Literal["success", "partial", "blocked", "failed"] = Field(
        ...,
        description="Execution status of the sub-task."
    )
    confidence: Literal["high", "medium", "low"] = Field(
        ...,
        description="Agent's confidence in the completeness and accuracy of the result."
    )
    result: str = Field(
        ...,
        description="The primary output or answer generated by the agent."
    )
    facts: list[str] = Field(
        default_factory=list,
        description="Concrete, verifiable facts extracted or retrieved."
    )
    unknowns: list[str] = Field(
        default_factory=list,
        description="Information that was requested but could not be found."
    )
    constraints: list[str] = Field(
        default_factory=list,
        description="Business rules, policy limitations, or strict constraints discovered."
    )
